### ISSUE TITLE
[Bug] Inconsistent column specifications for `accounts`

### ISSUE THREAD

**Issue by raphaelvarieras** [fivetran/dbt_zuora_source#10]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

The `account` entity has a different column specification between the source YAML file, the model file, and the model YAML file. Specifically, what is causing a problem for me right now is that these two columns are missing from the staging model, and cannot be added using passthrough columns without resulting in an error:
- unapplied_balance
- unapplied_credit_memo_amount

### Relevant error log or model output

```shell
If trying to passthrough:
Database Error in model stg_zuora__account (models/stg_zuora__account.sql)
  002028 (42601): SQL compilation error:
  ambiguous column name 'UNAPPLIED_BALANCE'
  compiled Code at target/run/zuora_source/models/stg_zuora__account.sql

Without passthrough, the columns are simply missing
```

### Expected behavior

The columns spec should match between the three files, and include important columns like the ones mentioned above. Note that these columns are only present when the tenant is using the Invoice Settlement feature.

### dbt Project configurations

N/A

### Package versions

0.2.0

### What database are you using dbt with?

snowflake

### dbt Version

1.6

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-avinash** [comment]
Hi @raphaelvarieras , thanks for bringing this to our attention. You are correct that these fields need to be removed from the macro, as adding them to passthrough columns is causing them to be called twice. We will pick up work on this in a coming sprint, likely bundled in with the fixes on the `dbt_zuora` package.
